start: pokemon

value: object | array | STRING | NUMBER | BOOLEAN | NULL

pokemon: "{\"name\":" STRING "," pair+ ",\"preEvolution\":" (STRING | NULL) "}"

object: "{" [pair ("," pair)*] "}"
pair: STRING ":" value
array: "[" [value ("," value)*] "]"

BOOLEAN: "true" | "false"
STRING: /"(\\.|[^"\\])*"/
NUMBER: /-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?/
NULL: "null"
%import common.WS
%ignore WS