// Lark Grammar for SQLite .test files
?start: test_suite

test_suite: (test_case | COMMENT | NEWLINE)*

test_case: "do_test" test_name "{" script_body "}" "{" result_body "}"

test_name: TEST_ID

script_body: inner_content
result_body: inner_content

inner_content: ( /[^}{]/ | "{" inner_content "}" )*

TEST_ID: /[a-zA-Z0-9._:-]+/

%import common.SH_COMMENT -> COMMENT
%import common.NEWLINE
%import common.WS

%ignore WS